apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
  namespace: default
  labels:
    app: springboot-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32002
  selector:

    app: springboot-app

